export enum MessageType {
  TYPE_NONE = 100,
  TYPE_HANDSHAKE_REQUEST = 101,
  TYPE_HANDSHAKE_RESPONSE = 102,
  TYPE_CHANGE_STATE = 103,
  TYPE_RUN_DATA = 104,
  TYPE_RC_DATA = 105,
}

export enum State {
  STATE_DEMO1 = 0,
  STATE_DEMO2 = 1,
  STATE_DEMO3 = 2,
  STATE_DEMO4 = 3,
  STATE_DEMO5 = 4,
}
